### ISSUE TITLE
Compiling a libretro compatible core

### ISSUE THREAD

**Issue by thelamer** [nbarkhina/N64Wasm#2]
Great work here, this really works well.
I have been trying to put together a web based emulator frontend and would like to use a libretro based core for n64.
Looking over the code it looks like you swapped to SDL2 vs libretros glsym_es `#include <SDL2/SDL_opengl.h>`. Now I am not sure if this is even possible, but could you give me any pointers as to how to compile this into a bc file compatible with the libretro api/frontend? (standard `emmake make -f Makefile platform=emscripten` and `emmake make -f Makefile.emscripten LIBRETRO=parallel_n64`)

I got https://github.com/libretro/parallel-n64 to compile with some makefile tweaks, but it just aborts after loading a rom.
```
[libretro INFO] Microcode 0 - RSP SW 2.0X (Super Mario 64)
libretro.js:141 [libretro INFO] microcheck: old ucode: 2,  new ucode: 0
libretro.js:141 exception thrown: RuntimeError: unreachable,RuntimeError: unreachable
    at http://localhost:8000/data/parallel_n64_libretro.wasm:wasm-function[949]:0x3cdd3
    at http://localhost:8000/data/parallel_n64_libretro.wasm:wasm-function[3536]:0x122b6e
    at http://localhost:8000/data/parallel_n64_libretro.wasm:wasm-function[2731]:0xeafed
    at http://localhost:8000/data/parallel_n64_libretro.wasm:wasm-function[2775]:0xf0035
    at http://localhost:8000/data/parallel_n64_libretro.wasm:wasm-function[4930]:0x1752b6
    at http://localhost:8000/data/parallel_n64_libretro.wasm:wasm-function[4931]:0x175351
    at http://localhost:8000/data/parallel_n64_libretro.wasm:wasm-function[1925]:0x9ffcf
    at http://localhost:8000/data/parallel_n64_libretro.wasm:wasm-function[1924]:0x9fe42
    at http://localhost:8000/data/parallel_n64_libretro.wasm:wasm-function[4915]:0x1742fc
    at http://localhost:8000/data/parallel_n64_libretro.wasm:wasm-function[4916]:0x17437c
 ```

There is also this https://m4xw.net/retroarch/ based on some old mupen64 code, but it does not really function. I suspect your swap to SDL2 is gonna be needed, but I am not sure how to fit these puzzle pieces together and make a working core. In general in way over my head and wanted to reach out to you to just see if this would even be plausible. The goal being to have your n64 core changes run with the standard module init and interactive menu baked into the current emscripten libretro builds.

**Comment by nbarkhina** [comment]
Hi @thelamer 

If you can believe it, I actually initially started this project by trying to compile that same core for use inside the RetroArch Web Player https://web.libretro.com/ I remember I got it to compile but then it crashed when I tried to load up a game from the UX (probably similar to the output you pasted). My guess is there is something about the current version of RetroArch that makes it difficult to port anything past the 16/32 bit systems that did not have 3D capabilities. It may have something to do with the rendering code they use for the emscripten build and its support for OpenGL (I'm honestly not sure) But to make a long story short that is what eventually led me down the path of porting the core directly rather than trying to get it to work inside of RetroArch. It gave me way more control over low level rendering and API calls, and allowed me to eventually get it running (first in Windows and then in the Web via emscripten). My advice to you is if you are trying to make a compatible Libretro Core then I probably wouldn't use this codebase because I ripped out so much RetroArch stuff in order to get it to work that it's totally incompatible with the Libretro API at this point. The way you are compiling it is probably correct, I think the key lies somewhere in the RetroArch Host code (not the core) in order to get it to work. You should also try building a debug version of the bc file (-G4 instead of the usual -O3 optimized version) and also a debug version of the RetroArch host you are using. Otherwise it's hard to tell what the issue is in that stacktrace without knowing exactly where it's crashing. Also take a look at this article https://docs.libretro.com/development/cores/opengl-cores/ it describes the additional information around building "OpenGL Cores" for libretro. Hope that helps.

Thanks
