### ISSUE TITLE
Question: Where in your script do you start emulating the blur effect.

### ISSUE THREAD

**Issue by BeezBumba** [nbarkhina/N64Wasm#36]
I am wondering where inside the module script you start emulating the blurring of textures. I am scrapping the other issue.

**Comment by nbarkhina** [comment]
Take a look at line 1040 in libretronew.c

```
    retro_filtering = 1;
```

Try changing this to 0,2, or 3 that may be what you're looking for. it's synonymous with the same setting in the parallel-n64 retroarch core:

"(Glide64) Texture Filtering; automatic|N64 3-point|bilinear|nearest"

**Comment by BeezBumba** [comment]
I'm talking about the n64wasm.js file inside the dist folder.

**Comment by nbarkhina** [comment]
It's not in that file. You will need to recompile new versions of the n64wasm.js and n64wasm.wasm files yourself in order to make this change.

**Comment by BeezBumba** [comment]
Quick question, what does the code in the file do?

**Comment by nbarkhina** [comment]
Nj64wasm.js is what is generated by the Emscripten compiler to allow the webassembly file (N4wasm.wasm) be able to interact with the page. By default wasm files have no access to the DOM. It's also called "glue code"

**Comment by BeezBumba** [comment]
Did you label the Glide64 setting from 0 - 3, so automatic will be 0 and nearest is 3. What does the other ones do in 1044 and 1038?

**Comment by nbarkhina** [comment]
These are the values:

- automatic = 0
- N64 3-point =1
- nearest =2
- bilinear = 3

and in 'code\Makefile' remove `-DDISABLE_3POINT \` from line 169. after looking at it the better place to set it would be on line 832 since it looks like multiple locations call that function

```c
static void gfx_set_filtering(void)
{
   //set it here
   retro_filtering = 1;

    if (log_cb)
        log_cb(RETRO_LOG_DEBUG, "set filtering mode...\n");
    switch (gfx_plugin)
```

I'm not sure what the other setting on line 1044 does `retro_dithering` but you can try that as well. For that one 0 = disabled and 1 = enabled
